DemoEntityFramework/DemoEntityFramework.Web/Models/ShipperListadoModel.cs
using DemoEntityFramework.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DemoEntityFramework.Web.Models
{
    public class ShipperListadoModel
    {
        public ShipperListadoModel()
        {
            ListShippers = new List<Shippers>();
        }

        public int Cantidad { get; set; }
        public List<Shippers> ListShippers { get; set; }
    }
}

DemoEntityFramework/DemoEntityFramework.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoEntityFramework.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DemoEntityFramework/DemoEntityFramework.Web/Controllers/ShipperController.cs
using DemoEntityFramework.Entities;
using DemoEntityFramework.Logic;
using DemoEntityFramework.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoEntityFramework.Web.Controllers
{
    public class ShipperController : Controller
    {
        //01:48:31
        // GET: Shipper
        public ActionResult Index()
        {
            ILogic<Shippers> logic = new ShipperLogic();
            var shippers = logic.GetAll();
            return View(shippers);
        }

        public ActionResult Listado()
        {
            ILogic<Shippers> logic = new ShipperLogic();
            var shippers = logic.GetAll();
            var modelo = new ShipperListadoModel
            {
                ListShippers = shippers,
                Cantidad = shippers.Count
            };
            return View(modelo);
        }

        public ActionResult Delete(int id)
        {
            ILogic<Shippers> logic = new ShipperLogic();
            var shipper = logic.GetById(id);
            return View(shipper);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ILogic<Shippers> logic = new ShipperLogic();
            logic.Delete(id);
            return RedirectToAction("Listado");
        }

        public ActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public ActionResult Create(Shippers shipp)
        {
            ILogic<Shippers> logic = new ShipperLogic();
            logic.Add(shipp);
            return RedirectToAction("Listado");
        }

        public ActionResult Edit(int id)
        {
            ILogic<Shippers> logic = new ShipperLogic();
            var shipp = logic.GetById(id);
            return View(shipp);
        }

        [HttpPost]
        public ActionResult Edit(Shippers shipp)
        {
            ILogic<Shippers> logic = new ShipperLogic();
            logic.Update(shipp);
            return RedirectToAction("Listado");
        }        
    }
}

DemoEntityFramework/DemoEntityFramework.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DemoEntityFramework/DemoEntityFramework.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DemoEntityFramework/DemoEntityFramework.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

DemoEntityFramework/DemoEntityFramework.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Shippers", "Listado", "Shipper")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DemoEntityFramework/DemoEntityFramework.Web/Views/Shipper/Create.cshtml
@model DemoEntityFramework.Entities.Shippers

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Shippers</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoEntityFramework/DemoEntityFramework.Web/Views/Shipper/Delete.cshtml
@model DemoEntityFramework.Entities.Shippers

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Shippers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Listado")
        </div>
    }
</div>

DemoEntityFramework/DemoEntityFramework.Web/Views/Shipper/Edit.cshtml
@model DemoEntityFramework.Entities.Shippers

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Shippers</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShipperID)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoEntityFramework/DemoEntityFramework.Web/Views/Shipper/Index.cshtml
@model List<DemoEntityFramework.Entities.Shippers>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>COMPANY NAME</th>
            <th>PHONE</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ShipperID</td>
                <td>@item.CompanyName</td>
                <td>@item.Phone</td>
            </tr>
        }            
        </tbody>
</table>

DemoEntityFramework/DemoEntityFramework.Web/Views/Shipper/Listado.cshtml
@model DemoEntityFramework.Web.Models.ShipperListadoModel

@{
    ViewBag.Title = "Listado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listado</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<span>Cantidad de Registros: </span>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ListShippers.First().CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ListShippers.First().Phone)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.ListShippers) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ShipperID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ShipperID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ShipperID })
        </td>
    </tr>
}

</table>